version: '3.4'

services:
    mysql:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_DATABASE: booking
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        ports:
            - '3306:3306'
        volumes:
            - my-db:/var/lib/mysql
volumes:
    my-db:
